version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules # Mount a named volume for node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_FORCE_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host

  prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    # For a typical SPA, the 'prod' service serves static files
    # and doesn't usually depend on the 'app' (development) service being running.
    # Removing depends_on here to avoid potential circular dependencies or unnecessary waits.
    # If 'prod' specifically needs 'app' to be up for some reason, you can add it back.
    # depends_on:
    #   - app
    restart: unless-stopped

volumes:
  app_node_modules: # Define the named volume here
